[[function-score-query]]
=== function_score 查询

{ref}/query-dsl-function-score-query.html[`function_score` 查询]
是用来控制评分过程的终极武器，它允许为每个与主查询匹配的文档应用一个函数，((("function_score query")))((("relevance", "controlling", "function_score query")))以达到改变甚至完全替换原始查询评分 `_score` 的目的。

实际上，也能用过滤器对结果的 _子集_ 应用不同的函数，这样一箭双雕：既能高效评分，又能利用过滤器缓存。

Elasticsearch 预定义了一些函数：

`weight`::

    为每个文档应用一个简单而不被规范化的权重提升值：当 `weight` 为 `2` 时，最终结果为 `2 * _score` 。

`field_value_factor`::

    使用这个值来修改 `_score` ，如将 `popularity` 或 `votes` （受欢迎或赞）作为考虑因素。

`random_score`::

    为每个用户都使用一个不同的随机评分对结果排序，但对某一具体用户来说，看到的顺序始终是一致的。

_衰减函数_ —— `linear` 、 `exp` 、 `gauss`::

    将评分与浮动值一起使用，如 `publish_date` 、 `geo_location` 、 `price` 提供偏好最近发布文档的评分 `_score` ，某一具体经纬度（lat/lon）位置附近的文档，或某一具体价格附近的文档。

`script_score`::

    如果需求超出以上范围时，用自定义脚本可以完全控制评分计算，实现所需逻辑。

如果没有 `function_score` 查询，就不能将全文查询与最新发生这种因子结合在一起评分，而需要对评分 `_score` 或时间 `date` 进行排序；这会相互影响抵消两种排序各自的效果。这个查询可以使两个效果融合，仍然按照全文相关度进行排序，只是会有更多考虑：最近发布的文档、流行的文档、或用户在意的价格区间。正如所设想的，查询要考虑所有这些因素会非常复杂，让我们先从简单的例子开始，然后顺着梯子慢慢向上爬，增加复杂度。
